<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(StormPortableTfm)</TargetFramework>
    <RootNamespace>StormOS.Security.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\StormOS.Core\StormOS.Core.csproj" />
    <ProjectReference Include="..\..\src\StormOS.Security\StormOS.Security.csproj" />
  </ItemGroup>
</Project>
