# Storm branding and OOBE: assets, default theme, OEM information, oobe.xml and the answer file.
# Only documented OEM customization points are used; Microsoft files, logos and Setup are not modified.

function Get-StormBrandingConfig {
  param([Parameter(Mandatory)] [System.Collections.IDictionary] $Paths)
  $config = Read-StormJson -Path (Join-Path $Paths.Config 'branding\branding.json')
  foreach ($field in 'productName', 'statement', 'oem', 'theme', 'assets', 'colors') {
    if (-not $config.Contains($field)) {
      throw (New-StormError -Code Customization -Message "config/branding/branding.json is missing '$field'." -Fix 'Restore the file from the repository.')
    }
  }
  return $config
}

function ConvertTo-StormThemeColor {
  <# "#RRGGBB" -> "0XFFRRGGBB" as used by ColorizationColor in .theme files. #>
  param([Parameter(Mandatory)] [string] $Hex)
  if ($Hex -notmatch '^#([0-9A-Fa-f]{6})$') { throw (New-StormError -Code Customization -Message "Invalid color '$Hex' (expected #RRGGBB)." -Fix 'Fix config/branding/branding.json.') }
  return '0XFF' + $Matches[1].ToUpperInvariant()
}

function New-StormThemeContent {
  <# Builds the StormOS.theme file (INI). Windows reads .theme files as UTF-16; the writer uses Unicode encoding. #>
  param([Parameter(Mandatory)] [System.Collections.IDictionary] $Branding)
  $theme = $Branding.theme
  $mode = if ($theme.darkMode) { 'Dark' } else { 'Light' }
  $lines = @(
    '; STORM OS default theme. Generated by scripts/05-apply-branding.ps1 from config/branding/branding.json.'
    '[Theme]'
    "DisplayName=$($theme.displayName)"
    ''
    '[Control Panel\Desktop]'
    "Wallpaper=$($theme.wallpaper)"
    'TileWallpaper=0'
    'WallpaperStyle=10'
    'Pattern='
    ''
    '[VisualStyles]'
    'Path=%SystemRoot%\resources\Themes\Aero\Aero.msstyles'
    'ColorStyle=NormalColor'
    'Size=NormalSize'
    'AutoColorization=0'
    "ColorizationColor=$(ConvertTo-StormThemeColor $Branding.colors.accent)"
    "SystemMode=$mode"
    "AppMode=$mode"
    ''
    '[MasterThemeSelector]'
    'MTSM=RJSPBS'
    ''
    '[Sounds]'
    '; Storm sounds are not implemented yet (branding/sounds/README.md); the Windows default scheme is kept.'
    'SchemeName=@%SystemRoot%\System32\mmres.dll,-800'
    ''
    '[boot]'
    'SCRNSAVE.EXE='
  )
  return ($lines -join "`r`n") + "`r`n"
}

function Get-StormBrandingRegistrySettings {
  <#
    Registry values for branding, declared like every other default: OEM information (Settings > System > About)
    and the default theme for new user profiles. Model text states honestly that this is a Storm customization of
    the selected Windows edition.
  #>
  param([Parameter(Mandatory)] [System.Collections.IDictionary] $Branding, [Parameter(Mandatory)] [string] $EditionName)
  $oem = $Branding.oem
  $model = ([string]$oem.modelTemplate).Replace('{edition}', $EditionName)
  $settings = @(
    [ordered]@{ id = 'branding.oem-manufacturer'; name = 'OEM manufacturer'; description = 'Shown in Settings > System > About.'; reason = 'Identifies the STORM OS customization.'; category = 'BRANDING'; risk = 'None'; hive = 'Software'; key = 'Microsoft\Windows\CurrentVersion\OEMInformation'; valueName = 'Manufacturer'; type = 'REG_SZ'; value = $oem.manufacturer; editions = @('*'); userChange = 'Informational only.' }
    [ordered]@{ id = 'branding.oem-model'; name = 'OEM model'; description = 'Shown in Settings > System > About.'; reason = 'States that this is a Storm customization of the installed Windows edition.'; category = 'BRANDING'; risk = 'None'; hive = 'Software'; key = 'Microsoft\Windows\CurrentVersion\OEMInformation'; valueName = 'Model'; type = 'REG_SZ'; value = $model; editions = @('*'); userChange = 'Informational only.' }
    [ordered]@{ id = 'branding.oem-support-url'; name = 'Support URL'; description = 'Support link in Settings > System > About.'; reason = 'Points users to STORM OS support instead of the hardware vendor.'; category = 'BRANDING'; risk = 'None'; hive = 'Software'; key = 'Microsoft\Windows\CurrentVersion\OEMInformation'; valueName = 'SupportURL'; type = 'REG_SZ'; value = $oem.supportUrl; editions = @('*'); userChange = 'Informational only.' }
    [ordered]@{ id = 'branding.oem-logo'; name = 'OEM logo'; description = 'Logo shown next to the OEM information.'; reason = 'Storm branding.'; category = 'BRANDING'; risk = 'None'; hive = 'Software'; key = 'Microsoft\Windows\CurrentVersion\OEMInformation'; valueName = 'Logo'; type = 'REG_EXPAND_SZ'; value = $oem.logo; editions = @('*'); userChange = 'Informational only.' }
    [ordered]@{ id = 'branding.default-theme'; name = 'Default theme for new users'; description = 'New user profiles start with the STORM OS theme (wallpaper, dark mode, accent color).'; reason = 'Storm desktop experience.'; category = 'BRANDING'; risk = 'None'; hive = 'Software'; key = 'Microsoft\Windows\CurrentVersion\Themes'; valueName = 'InstallTheme'; type = 'REG_EXPAND_SZ'; value = $Branding.theme.target; editions = @('*'); userChange = 'Settings > Personalization > Themes.' }
  )
  $lock = $Branding.lockScreen
  if ($lock -and @($lock.enforceOnEditions).Count -gt 0) {
    # Windows only offers an enforced lock screen image (policy) on Enterprise/Education; it is opt-in per edition.
    $settings += [ordered]@{ id = 'branding.lock-screen'; name = 'Lock screen image'; description = 'Sets the STORM OS lock screen image by policy.'; reason = 'Storm lock screen; enforced, so the user cannot pick another image.'; category = 'BRANDING'; risk = 'Low'; hive = 'Software'; key = 'Policies\Microsoft\Windows\Personalization'; valueName = 'LockScreenImage'; type = 'REG_EXPAND_SZ'; value = $lock.target; editions = @($lock.enforceOnEditions); userChange = 'Remove the policy value (gpedit: Control Panel > Personalization).' }
  }
  return $settings
}

function Install-StormBrandingFiles {
  <# Copies branding assets into the mounted image and writes the theme file. Returns the installed files with hashes. #>
  param([Parameter(Mandatory)] [string] $MountPath, [Parameter(Mandatory)] [System.Collections.IDictionary] $Paths, [Parameter(Mandatory)] [System.Collections.IDictionary] $Branding, [string] $Phase = '05')
  $installed = New-Object System.Collections.Generic.List[object]
  foreach ($asset in @($Branding.assets)) {
    $source = Join-Path $Paths.Branding $asset.source
    if (-not (Test-Path -LiteralPath $source)) {
      throw (New-StormError -Code Customization -Message "Branding asset missing: $source" -Fix 'Regenerate assets with branding/tools/generate-branding.py or restore them from git.')
    }
    $target = Join-Path $MountPath $asset.target
    New-Item -ItemType Directory -Path (Split-Path -Parent $target) -Force | Out-Null
    Copy-Item -LiteralPath $source -Destination $target -Force
    $installed.Add([pscustomobject]@{ path = $asset.target; sha256 = Get-StormSha256 -Path $target })
    Write-StormLog -Phase $Phase -Message "asset $($asset.target)"
  }
  $themeTarget = Join-Path $MountPath 'Windows\Resources\Themes\StormOS.theme'
  New-Item -ItemType Directory -Path (Split-Path -Parent $themeTarget) -Force | Out-Null
  [System.IO.File]::WriteAllText($themeTarget, (New-StormThemeContent -Branding $Branding), [System.Text.Encoding]::Unicode)
  $installed.Add([pscustomobject]@{ path = 'Windows\Resources\Themes\StormOS.theme'; sha256 = Get-StormSha256 -Path $themeTarget })
  Write-StormLog -Phase $Phase -Message 'theme Windows\Resources\Themes\StormOS.theme'
  return $installed.ToArray()
}

function ConvertTo-StormXmlText {
  param([AllowEmptyString()] [string] $Value)
  return [System.Security.SecurityElement]::Escape($Value)
}

function New-StormOobeXml {
  <# OEM oobe.xml (Windows\System32\oobe\info): OEM name and logo during OOBE. No EULA or screen changes. #>
  param([Parameter(Mandatory)] [System.Collections.IDictionary] $Branding)
  $name = ConvertTo-StormXmlText $Branding.oem.manufacturer
  $logo = ConvertTo-StormXmlText $Branding.oobe.logo
  return @"
<?xml version="1.0" encoding="utf-8"?>
<!-- STORM OS OEM information for Windows OOBE. Generated by scripts/09-configure-oobe.ps1. -->
<FirstExperience>
  <oobe>
    <oem>
      <name>$name</name>
      <logopath>$logo</logopath>
    </oem>
  </oobe>
</FirstExperience>
"@
}

function ConvertTo-StormUnattendArchitecture {
  param([Parameter(Mandatory)] [string] $Architecture)
  switch ($Architecture) { 'x64' { return 'amd64' } 'arm64' { return 'arm64' } default { throw (New-StormError -Code Customization -Message "Unsupported architecture for the answer file: $Architecture" -Fix 'Use an x64 or ARM64 image.') } }
}

function New-StormUnattendXml {
  <#
    Answer file placed at Windows\Panther\unattend.xml inside the image. It only sets appearance defaults in the
    oobeSystem pass. It deliberately contains no windowsPE pass (no disk partitioning), no product key, no accounts,
    no automatic logon and no hardware-requirement or network bypasses: the user goes through normal Windows Setup.
  #>
  param([Parameter(Mandatory)] [System.Collections.IDictionary] $Branding, [Parameter(Mandatory)] [string] $Architecture)
  $arch = ConvertTo-StormUnattendArchitecture -Architecture $Architecture
  $theme = ConvertTo-StormXmlText $Branding.theme.target
  return @"
<?xml version="1.0" encoding="utf-8"?>
<!--
  STORM OS answer file: appearance defaults only. Generated by scripts/09-configure-oobe.ps1.
  Contains no disk configuration, product key, user account, auto logon or setup-requirement settings.
-->
<unattend xmlns="urn:schemas-microsoft-com:unattend" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State">
  <settings pass="oobeSystem">
    <component name="Microsoft-Windows-Shell-Setup" processorArchitecture="$arch" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
      <Themes>
        <CustomDefaultThemeFile>$theme</CustomDefaultThemeFile>
      </Themes>
    </component>
  </settings>
</unattend>
"@
}

function Test-StormUnattendSafety {
  <#
    Returns a list of violations for an answer file. STORM OS answer files must not partition disks, contain keys or
    credentials, log on automatically, skip the user's OOBE decisions or bypass hardware/network requirements.
  #>
  param([Parameter(Mandatory)] [string] $XmlText)
  $violations = New-Object System.Collections.Generic.List[string]
  try { [xml]$document = $XmlText } catch { return @("not well-formed XML: $($_.Exception.Message)") }
  $namespace = New-Object System.Xml.XmlNamespaceManager($document.NameTable)
  $namespace.AddNamespace('u', 'urn:schemas-microsoft-com:unattend')
  if ($document.DocumentElement.LocalName -ne 'unattend') { $violations.Add('root element must be <unattend>') }
  foreach ($pass in $document.SelectNodes('//u:settings', $namespace)) {
    if ($pass.GetAttribute('pass') -eq 'windowsPE') { $violations.Add('windowsPE pass is not allowed (disk and setup decisions stay with the user)') }
  }
  $forbidden = @{
    'DiskConfiguration' = 'disk partitioning'; 'InstallTo' = 'target disk selection'; 'ProductKey' = 'product keys'; 'Key' = 'product keys'
    'UserAccounts' = 'user accounts'; 'AutoLogon' = 'automatic logon'; 'Password' = 'passwords'; 'AdministratorPassword' = 'passwords'
    'SkipMachineOOBE' = 'skipping OOBE'; 'SkipUserOOBE' = 'skipping OOBE'; 'HideOnlineAccountScreens' = 'hiding account choices'
    'HideEULAPage' = 'hiding the license terms'; 'ProtectYourPC' = 'pre-selecting privacy choices'; 'RunSynchronous' = 'commands during setup'
    'FirstLogonCommands' = 'commands at first logon'; 'LogonCommands' = 'commands at logon'
  }
  foreach ($element in $document.SelectNodes('//*')) {
    if ($forbidden.ContainsKey($element.LocalName)) { $violations.Add("<$($element.LocalName)> is not allowed ($($forbidden[$element.LocalName]))") }
  }
  if ($XmlText -match '(?i)Bypass(TPM|SecureBoot|RAM|Storage|CPU|NRO)|LabConfig|AllowUpgradesWithUnsupportedTPMOrCPU') {
    $violations.Add('setup requirement or network bypasses are not allowed')
  }
  return $violations.ToArray()
}
