<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(StormWindowsTfm)</TargetFramework>
    <RootNamespace>StormOS.Performance.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\StormOS.Core\StormOS.Core.csproj" />
    <ProjectReference Include="..\..\src\StormOS.Performance\StormOS.Performance.csproj" />
  </ItemGroup>
</Project>
