<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(StormWindowsTfm)</TargetFramework>
    <RootNamespace>StormOS.Games.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\StormOS.Core\StormOS.Core.csproj" />
    <ProjectReference Include="..\..\src\StormOS.Games\StormOS.Games.csproj" />
  </ItemGroup>
</Project>
