<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(StormWindowsTfm)</TargetFramework>
    <RootNamespace>StormOS.Hardware.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\StormOS.Core\StormOS.Core.csproj" />
    <ProjectReference Include="..\..\src\StormOS.Windows\StormOS.Windows.csproj" />
    <ProjectReference Include="..\..\src\StormOS.Hardware\StormOS.Hardware.csproj" />
  </ItemGroup>
</Project>
