<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(StormPortableTfm)</TargetFramework>
    <RootNamespace>StormOS.Network.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\StormOS.Core\StormOS.Core.csproj" />
    <ProjectReference Include="..\..\src\StormOS.Network\StormOS.Network.csproj" />
  </ItemGroup>
</Project>
