<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(StormPortableTfm)</TargetFramework>
    <RootNamespace>StormOS.Infrastructure.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\StormOS.Core\StormOS.Core.csproj" />
    <ProjectReference Include="..\..\src\StormOS.Infrastructure\StormOS.Infrastructure.csproj" />
  </ItemGroup>
</Project>
